# Generated by Django 6.0 on 2025-12-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple_admin', '0003_memberprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_multiple_bookings', models.BooleanField(default=False, help_text='Allow members to book the same pooja multiple times')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
                'constraints': [models.UniqueConstraint(fields=('id',), name='single_site_settings')],
            },
        ),
    ]
