# Generated by Django 5.2.8 on 2025-12-15 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relation_type', models.CharField(choices=[('Root', 'Head of Family (Root)'), ('Spouse', 'Spouse (Wife/Husband)'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Daughter-in-law', 'Daughter-in-law'), ('Son-in-law', 'Son-in-law')], max_length=50)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='family_pics/')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Select the associated family member (e.g., Father or Husband)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='family_tree.familymember')),
            ],
        ),
    ]
