# Generated by Django 5.2.8 on 2025-12-15 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Select the parent (e.g. Father/Mother). Leave empty if this is the Head of Family.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='family_tree.familymember'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation_type',
            field=models.CharField(help_text='e.g. Son, Daughter, Wife, Head of Family', max_length=50),
        ),
    ]
