# Generated by Django 5.2.8 on 2025-12-15 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0002_familymember_created_at_alter_familymember_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Families',
            },
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='created_at',
        ),
        migrations.AddField(
            model_name='familymember',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='spouse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='husband_or_wife', to='family_tree.familymember'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='family_tree.familymember'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation_type',
            field=models.CharField(choices=[('Head', 'Head of Family'), ('Spouse', 'Spouse'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Father', 'Father'), ('Mother', 'Mother')], max_length=50),
        ),
        migrations.AddField(
            model_name='familymember',
            name='family_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='family_tree.family'),
        ),
    ]
