# Generated by Django 5.2.8 on 2025-12-15 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0003_family_remove_familymember_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={},
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(help_text='e.g. The Gupta Family', max_length=100),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation_type',
            field=models.CharField(choices=[('Root', 'Head of Family'), ('Spouse', 'Spouse'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Father', 'Father'), ('Mother', 'Mother')], max_length=50),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='spouse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner', to='family_tree.familymember'),
        ),
    ]
