# Generated by Django 5.2.8 on 2025-12-15 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0004_alter_family_options_alter_family_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name_plural': 'Families'},
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(help_text='Family Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Biological parent. Leave empty for the Root ancestor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='family_tree.familymember'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation_type',
            field=models.CharField(help_text='e.g. Father, Aunt, Root', max_length=50),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='spouse',
            field=models.OneToOneField(blank=True, help_text='Current spouse.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner', to='family_tree.familymember'),
        ),
    ]
