# Generated by Django 5.2.8 on 2025-12-16 05:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0005_alter_family_options_alter_family_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='family_group',
        ),
        migrations.AlterModelOptions(
            name='familymember',
            options={'ordering': ['name'], 'verbose_name': 'Family Member', 'verbose_name_plural': 'Family Members'},
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='familymember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familymember',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familymember',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='Leave blank if alive', null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='familymember',
            name='is_root',
            field=models.BooleanField(default=False, help_text='Is this the root/starting person?'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='familymember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='family_photos/'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='notes',
            field=models.TextField(blank=True, default=0, help_text='Any additional notes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='familymember',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Select parent (father or mother)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='family_tree.familymember'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='spouse',
            field=models.ForeignKey(blank=True, help_text='Select spouse', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='married_to', to='family_tree.familymember'),
        ),
        migrations.CreateModel(
            name='FamilyTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Family name (e.g., 'Smith Family')", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_trees', to=settings.AUTH_USER_MODEL)),
                ('root_member', models.ForeignKey(blank=True, help_text='Starting person of this tree', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_of_tree', to='family_tree.familymember')),
            ],
            options={
                'verbose_name': 'Family Tree',
                'verbose_name_plural': 'Family Trees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Family',
        ),
    ]
