# Generated by Django 5.2.8 on 2025-12-16 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0006_remove_familymember_family_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={},
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='is_root',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='familymember',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='family_tree.familymember'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse_ref', to='family_tree.familymember'),
        ),
        migrations.DeleteModel(
            name='FamilyTree',
        ),
    ]
