# Generated by Django 5.2.8 on 2025-12-16 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0007_alter_familymember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='spouse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse_of', to='family_tree.familymember'),
        ),
    ]
