# Generated by Django 5.2.8 on 2025-12-16 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0008_alter_familymember_spouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse_ref', to='family_tree.familymember'),
        ),
    ]
