# Generated by Django 4.2.27 on 2026-01-02 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0009_alter_familymember_spouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='spouse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverse_spouse', to='family_tree.familymember'),
        ),
    ]
