# Generated by Django 4.2.27 on 2026-01-07 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0010_alter_familymember_spouse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='familymember',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='is_deceased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse_ref', to='family_tree.familymember'),
        ),
    ]
