# Generated by Django 4.2.27 on 2026-01-07 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0011_alter_familymember_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={},
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='is_deceased',
        ),
        migrations.AlterField(
            model_name='familymember',
            name='spouse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverse_spouse', to='family_tree.familymember'),
        ),
    ]
