# Generated by Django 5.2.8 on 2025-12-08 05:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('pooja', '0007_delete_poojabooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='poojabooking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='devotee_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='nakshatra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='order_id',
            field=models.CharField(blank=True, help_text='Razorpay order ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Razorpay payment ID', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='signature',
            field=models.CharField(blank=True, help_text='Razorpay signature for verification', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='poojabooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('completed', 'Completed'), ('failed', 'Payment Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='poojabooking',
            unique_together={('user', 'pooja', 'status')},
        ),
        migrations.AddIndex(
            model_name='poojabooking',
            index=models.Index(fields=['user', '-booked_at'], name='pooja_booki_user_id_ca85a0_idx'),
        ),
        migrations.AddIndex(
            model_name='poojabooking',
            index=models.Index(fields=['status', '-booked_at'], name='pooja_booki_status_ad8b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='poojabooking',
            index=models.Index(fields=['payment_id'], name='pooja_booki_payment_0c2bdb_idx'),
        ),
    ]
