# Generated by Django 5.2.8 on 2025-12-08 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_poojabooking_unique_together_and_more'),
        ('pooja', '0007_delete_poojabooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='poojabooking',
            name='pooja_booki_status_ad8b4a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='poojabooking',
            unique_together={('user', 'pooja')},
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='payment_completed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When payment was actually completed', null=True),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Payment Pending'), ('completed', 'Payment Completed'), ('failed', 'Payment Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, help_text='When payment signature was verified', null=True),
        ),
        migrations.AlterField(
            model_name='poojabooking',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid in INR', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='poojabooking',
            name='devotee_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='poojabooking',
            name='order_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='poojabooking',
            name='payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='poojabooking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='poojabooking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='booked', max_length=20),
        ),
        migrations.AddIndex(
            model_name='poojabooking',
            index=models.Index(fields=['order_id'], name='pooja_booki_order_i_17d955_idx'),
        ),
        migrations.AddIndex(
            model_name='poojabooking',
            index=models.Index(fields=['payment_status'], name='pooja_booki_payment_244a90_idx'),
        ),
        migrations.RemoveField(
            model_name='poojabooking',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='poojabooking',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='poojabooking',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='poojabooking',
            name='updated_at',
        ),
    ]
