# Generated by Django 6.0 on 2025-12-11 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_poojabooking_pooja_booki_status_ad8b4a_idx_and_more'),
        ('pooja', '0007_delete_poojabooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in INR', max_digits=10)),
                ('payment_mode', models.CharField(choices=[('upi_online', 'UPI Online'), ('upi_qr', 'UPI QR Code'), ('cash', 'Cash')], help_text='Payment method used', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', help_text='Payment status', max_length=20)),
                ('reference_id', models.CharField(blank=True, help_text='UPI transaction reference (for QR payments)', max_length=100, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Payment gateway transaction ID (Razorpay)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes (reason for failure, etc.)', null=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True, help_text='When payment was confirmed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When record was last updated')),
            ],
            options={
                'db_table': 'payment_history',
                'ordering': ['-confirmed_at'],
            },
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When admin approved this booking', null=True),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When booking was cancelled', null=True),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI Online'), ('upi_qr', 'UPI QR Code'), ('cash', 'Cash')], db_index=True, default='upi', help_text='Payment method: online UPI, offline QR, or cash', max_length=20),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved/cancelled this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poojabooking',
            name='order_id',
            field=models.CharField(blank=True, db_index=True, help_text='Razorpay order ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='poojabooking',
            name='payment_id',
            field=models.CharField(blank=True, db_index=True, help_text='Razorpay payment ID (online only)', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='poojabooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='poojabooking',
            index=models.Index(fields=['status'], name='pooja_booki_status_b66219_idx'),
        ),
        migrations.AddIndex(
            model_name='poojabooking',
            index=models.Index(fields=['payment_method'], name='pooja_booki_payment_23210c_idx'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='booking',
            field=models.ForeignKey(help_text='Associated booking', on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='booking.poojabooking'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who confirmed this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['booking', '-confirmed_at'], name='payment_his_booking_e1a717_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['payment_mode'], name='payment_his_payment_7fff0f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['status'], name='payment_his_status_4aff87_idx'),
        ),
    ]
