# Generated by Django 5.2.8 on 2025-12-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_paymenthistory_poojabooking_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poojabooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_cash', 'Pending Cash'), ('paid_online', 'Paid Online'), ('paid_cash', 'Paid Cash'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
    ]
