# Generated by Django 6.0 on 2025-12-19 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_poojabooking_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(help_text='Email recipient', max_length=254)),
                ('subject', models.CharField(help_text='Email subject line', max_length=200)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', help_text='Email delivery status', max_length=20)),
                ('attempts', models.IntegerField(default=1, help_text='Number of send attempts')),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the email was first attempted')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the email was successfully sent', null=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Associated booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='booking.poojabooking')),
            ],
            options={
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='email_logs_recipie_b50fb3_idx'), models.Index(fields=['status'], name='email_logs_status_e3be55_idx'), models.Index(fields=['booking'], name='email_logs_booking_2f9f25_idx')],
            },
        ),
    ]
