# Generated by Django 6.0 on 2025-12-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_emaillog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='poojabooking',
            unique_together=set(),
        ),
    ]
