# Generated by Django 5.2.8 on 2025-11-24 19:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('token_refresh', 'Token Refresh'), ('view_dashboard', 'View Dashboard'), ('view_profile', 'View Profile'), ('update_profile', 'Update Profile'), ('create_member', 'Create Member'), ('view_bookings', 'View Bookings'), ('create_booking', 'Create Booking'), ('other', 'Other Action')], help_text='Type of action performed', max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the action occurred')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser/device information', max_length=500)),
                ('is_admin', models.BooleanField(db_index=True, default=False, help_text='Whether action was performed by admin')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the action')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='main_activi_timesta_c39e8d_idx'), models.Index(fields=['user', '-timestamp'], name='main_activi_user_id_643867_idx'), models.Index(fields=['action', '-timestamp'], name='main_activi_action_179ae9_idx')],
            },
        ),
    ]
