# Generated by Django 6.0 on 2025-12-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_gallery'),
        ('main', '0004_delete_memberprofile'),
    ]

    operations = [
    ]
