# Generated by Django 5.2.8 on 2025-12-17 05:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_gallery_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='cloudinary_public_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
