# Generated by Django 5.2.8 on 2025-11-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooja',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
