# Generated by Django 5.2.8 on 2025-12-01 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0002_alter_pooja_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pooja',
            name='available_slots',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
