# Generated by Django 5.2.8 on 2025-12-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0003_pooja_available_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='pooja',
            name='max_slots',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pooja',
            name='available_slots',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
