# Generated by Django 5.2.8 on 2025-12-02 07:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0004_pooja_max_slots_alter_pooja_available_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooja',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MaxValueValidator(Decimal('10000000'))]),
        ),
    ]
