# Generated by Django 5.2.8 on 2025-12-03 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0005_alter_pooja_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoojaBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='booked', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('pooja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='pooja.pooja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pooja_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pooja_bookings',
                'ordering': ['-booked_at'],
                'unique_together': {('user', 'pooja')},
            },
        ),
    ]
