# Generated by Django 5.2.8 on 2025-12-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0006_poojabooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PoojaBooking',
        ),
    ]
