# Generated by Django 6.0 on 2025-12-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0007_delete_poojabooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='pooja',
            name='enable_slots',
            field=models.BooleanField(default=False, help_text='Enable/disable slot booking for this pooja'),
        ),
    ]
