# Generated by Django 4.2.27 on 2026-01-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0008_pooja_enable_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooja',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='pooja',
            constraint=models.UniqueConstraint(fields=('name', 'pooja_date'), name='unique_pooja_name_date'),
        ),
    ]
