# Generated by Django 4.2.27 on 2026-01-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0009_alter_pooja_name_pooja_unique_pooja_name_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pooja',
            name='allow_multiple_bookings',
            field=models.BooleanField(default=False, help_text='Allow multiple bookings for this pooja by the same user'),
        ),
    ]
